class Alumnogrupocurso:
    def __init__(self,IDALUMNOGRUPOCURSO, ALUMNO_DNI, IDGRUPOCURSO):
       self.IDALUMNOGRUPOCURSO = IDALUMNOGRUPOCURSO  # NUMBER
       self.ALUMNO_DNI = ALUMNO_DNI  # NUMBER
       self.IDGRUPOCURSO = IDGRUPOCURSO  # NUMBER
