class Credencialingreso:
    def __init__(self,IDCREDENCIALINGRESO, CORREO, CONTRASENIA, ALUMNO_DNI, DOCENTE_DNI):
       self.IDCREDENCIALINGRESO = IDCREDENCIALINGRESO  # NUMBER
       self.CORREO = CORREO  # VARCHAR2
       self.CONTRASENIA = CONTRASENIA  # VARCHAR2
       self.ALUMNO_DNI = ALUMNO_DNI  # NUMBER
       self.DOCENTE_DNI = DOCENTE_DNI  # NUMBER
