class Curso:
    def __init__(self,IDCURSO, NOMBRE, DESCRIPCION, IDPLANESTUDIO):
       self.IDCURSO = IDCURSO  # NUMBER
       self.NOMBRE = NOMBRE  # VARCHAR2
       self.DESCRIPCION = DESCRIPCION  # VARCHAR2
       self.IDPLANESTUDIO = IDPLANESTUDIO  # NUMBER
