class Docente:
    def __init__(self,DNI, NOMBRES, APELLIDOS, FECHANACIMIENTO, DIRECCION, TELEFONO):
       self.DNI = DNI  # NUMBER
       self.NOMBRES = NOMBRES  # VARCHAR2
       self.APELLIDOS = APELLIDOS  # VARCHAR2
       self.FECHANACIMIENTO = FECHANACIMIENTO  # DATE
       self.DIRECCION = DIRECCION  # VARCHAR2
       self.TELEFONO = TELEFONO  # NUMBER
