class Evaluaciontema:
    def __init__(self,IDEVALUACIONTEMA, TEMA_IDTEMA, EVALUACION_IDEVALUACION):
       self.IDEVALUACIONTEMA = IDEVALUACIONTEMA  # NUMBER
       self.TEMA_IDTEMA = TEMA_IDTEMA  # NUMBER
       self.EVALUACION_IDEVALUACION = EVALUACION_IDEVALUACION  # NUMBER
