class Evaluacionalumno:
    def __init__(self,IDEVALUACIONALUMNO, IDALUMNOGRUPOCURSO, FECHAHORAINICIO, FECHAHORAFINALIZACION):
       self.IDEVALUACIONALUMNO = IDEVALUACIONALUMNO  # NUMBER
       self.IDALUMNOGRUPOCURSO = IDALUMNOGRUPOCURSO  # NUMBER
       self.FECHAHORAINICIO = FECHAHORAINICIO  # TIMESTAMP(6)
       self.FECHAHORAFINALIZACION = FECHAHORAFINALIZACION  # TIMESTAMP(6)
