class Evaluacion:
    def __init__(self,IDEVALUACION, NOMBRE, DESCRIPCION, PORCENTAJECURSO, CANTIDADPREGUNTASGANAR, CANTIDADPREGUNTASALUMNO, FECHAHORAINICIO, FECHAHORAFINALIZACION, DOCENTE_DNI, IDTIPOEVALUACION, IDCATEGORIA):
       self.IDEVALUACION = IDEVALUACION  # NUMBER
       self.NOMBRE = NOMBRE  # VARCHAR2
       self.DESCRIPCION = DESCRIPCION  # VARCHAR2
       self.PORCENTAJECURSO = PORCENTAJECURSO  # NUMBER
       self.CANTIDADPREGUNTASGANAR = CANTIDADPREGUNTASGANAR  # NUMBER
       self.CANTIDADPREGUNTASALUMNO = CANTIDADPREGUNTASALUMNO  # NUMBER
       self.FECHAHORAINICIO = FECHAHORAINICIO  # TIMESTAMP(6)
       self.FECHAHORAFINALIZACION = FECHAHORAFINALIZACION  # TIMESTAMP(6)
       self.DOCENTE_DNI = DOCENTE_DNI  # NUMBER
       self.IDTIPOEVALUACION = IDTIPOEVALUACION  # NUMBER
       self.IDCATEGORIA = IDCATEGORIA  # NUMBER
