class Horariogrupocurso:
    def __init__(self,IDHORARIOGRUPOCURSO, IDGRUPOCURSO, DIA, HORAINICIO, HORAFINALIZACION):
       self.IDHORARIOGRUPOCURSO = IDHORARIOGRUPOCURSO  # NUMBER
       self.IDGRUPOCURSO = IDGRUPOCURSO  # NUMBER
       self.DIA = DIA  # VARCHAR2
       self.HORAINICIO = HORAINICIO  # VARCHAR2
       self.HORAFINALIZACION = HORAFINALIZACION  # VARCHAR2
