class Planestudiounidad:
    def __init__(self,IDPLANESTUDIOUNIDAD, UNIDAD_IDUNIDAD, IDPLANESTUDIO):
       self.IDPLANESTUDIOUNIDAD = IDPLANESTUDIOUNIDAD  # NUMBER
       self.UNIDAD_IDUNIDAD = UNIDAD_IDUNIDAD  # NUMBER
       self.IDPLANESTUDIO = IDPLANESTUDIO  # NUMBER
