class Planestudio:
    def __init__(self,IDPLANESTUDIO, TITULO, DESCRIPCION):
       self.IDPLANESTUDIO = IDPLANESTUDIO  # NUMBER
       self.TITULO = TITULO  # VARCHAR2
       self.DESCRIPCION = DESCRIPCION  # VARCHAR2
