class Preguntaevaluacionalumno:
    def __init__(self,IDPREGUNTAEVALUACIONALUMNO, IDPREGUNTAEVALUACION, IDEVALUACIONALUMNO, TIEMPOPREGUNTA):
       self.IDPREGUNTAEVALUACIONALUMNO = IDPREGUNTAEVALUACIONALUMNO  # NUMBER
       self.IDPREGUNTAEVALUACION = IDPREGUNTAEVALUACION  # NUMBER
       self.IDEVALUACIONALUMNO = IDEVALUACIONALUMNO  # NUMBER
       self.TIEMPOPREGUNTA = TIEMPOPREGUNTA  # VARCHAR2
