class Preguntaevaluacion:
    def __init__(self,IDPREGUNTAEVALUACION, IDPREGUNTA, IDEVALUACION, PORCENTAJEPREGUNTA):
       self.IDPREGUNTAEVALUACION = IDPREGUNTAEVALUACION  # NUMBER
       self.IDPREGUNTA = IDPREGUNTA  # NUMBER
       self.IDEVALUACION = IDEVALUACION  # NUMBER
       self.PORCENTAJEPREGUNTA = PORCENTAJEPREGUNTA  # NUMBER
