class Pregunta:
    def __init__(self,IDPREGUNTA, ENUNCIADO, IDTIPOPREGUNTA, IDTEMA, IDVISIBILIDADPREGUNTA, DOCENTE_DNI):
       self.IDPREGUNTA = IDPREGUNTA  # NUMBER
       self.ENUNCIADO = ENUNCIADO  # VARCHAR2
       self.IDTIPOPREGUNTA = IDTIPOPREGUNTA  # NUMBER
       self.IDTEMA = IDTEMA  # NUMBER
       self.IDVISIBILIDADPREGUNTA = IDVISIBILIDADPREGUNTA  # NUMBER
       self.DOCENTE_DNI = DOCENTE_DNI  # NUMBER
