class Respuestapregunta:
    def __init__(self,IDRESPUESTAPREGUNTA, IDPREGUNTA, INTERROGANTE, OPCION, RESPUESTA):
       self.IDRESPUESTAPREGUNTA = IDRESPUESTAPREGUNTA  # NUMBER
       self.IDPREGUNTA = IDPREGUNTA  # NUMBER
       self.INTERROGANTE = INTERROGANTE  # VARCHAR2
       self.OPCION = OPCION  # VARCHAR2
       self.RESPUESTA = RESPUESTA  # VARCHAR2
