class Respuestaalumnoexamen:
    def __init__(self,IDRESPUESTAALUMNOEXAMEN, IDPREGUNTAEVALUACIONALUMNO, INTERROGANTE, OPCION, RESPUESTA):
       self.IDRESPUESTAALUMNOEXAMEN = IDRESPUESTAALUMNOEXAMEN  # NUMBER
       self.IDPREGUNTAEVALUACIONALUMNO = IDPREGUNTAEVALUACIONALUMNO  # NUMBER
       self.INTERROGANTE = INTERROGANTE  # VARCHAR2
       self.OPCION = OPCION  # VARCHAR2
       self.RESPUESTA = RESPUESTA  # VARCHAR2
