class Salongrupocurso:
    def __init__(self,IDSALONGRUPOCURSO, IDHORARIOGRUPOCURSO, IDSALON):
       self.IDSALONGRUPOCURSO = IDSALONGRUPOCURSO  # NUMBER
       self.IDHORARIOGRUPOCURSO = IDHORARIOGRUPOCURSO  # NUMBER
       self.IDSALON = IDSALON  # VARCHAR2
