class Visibilidadpregunta:
    def __init__(self,IDVISIBILIDADPREGUNTA, VISIBILIDAD):
       self.IDVISIBILIDADPREGUNTA = IDVISIBILIDADPREGUNTA  # NUMBER
       self.VISIBILIDAD = VISIBILIDAD  # VARCHAR2
